on:
  push:
    branches:
      - main
env:
    DOCKER_IMAGE: thuongbignose/busify-fe
    DOCKER_TAG: latest
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '20'
            cache: 'npm'
      - name: Install dependencies
        run: npm install

      - name: Run npm ci
        run: npm ci

      - name: Build the application
        id: build-next
        env:
            NEXT_PUBLIC_API_URL: ${{ secrets.PUBLIC_API_URL }}
        run: npm run build


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=${{ env.DOCKER_TAG }}
            type=semver,pattern={{version}}
          flavor: latest

      
      - name: Build Docker and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:cache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:cache,mode=max
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.PUBLIC_API_URL }}
          platforms: linux/amd64,linux/arm64
      - name: Image digest
        run: echo ${{ steps.build-next.outputs.image }}
      